# kyvernovis/charts/kyvernovis/values.yaml
replicaCount: 1

image:
  repository: parvez99/kyvernovis
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: kyvernovis.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}

nodeSelector: {}
tolerations: []
affinity: []
